DROP VIEW IF EXISTS `projects_datas`;
CREATE VIEW `projects_datas` AS select `projects`.`id` AS `id`,`projects`.`code` AS `code`,`projects`.`type` AS `type`,`projects`.`manager` AS `manager`,concat_ws(',',`projects`.`id`,`projects`.`name`,`projects`.`code`,`projects`.`type`,`projects`.`manager`,`projects`.`customer`,`projects`.`address`,`projects`.`vendor`,`projects`.`supplier`,`projects`.`location`,`projects`.`office`,`projects`.`start`,`projects`.`end`,`projects`.`budget`,`projects`.`summary`,`projects`.`budget_history`) AS `all_projects_datas` from `projects`;

DROP VIEW IF EXISTS `requisition_datas`;
CREATE VIEW `requisition_datas` AS select `tasks_requisition_bill`.`id` AS `id`,`tasks_requisition_bill`.`task_id` AS `task_id`,concat_ws(',',`tasks_requisition_bill`.`id`,`tasks_requisition_bill`.`task_id`,`tasks_requisition_bill`.`requisition_prepared_by_manager`,`tasks_requisition_bill`.`requisition_submitted_by_manager`,`tasks_requisition_bill`.`requisition_edited_by_cfo`,`tasks_requisition_bill`.`requisition_approved_by_cfo`,`tasks_requisition_bill`.`requisition_edited_by_accountant`,`tasks_requisition_bill`.`requisition_approved_by_accountant`,`tasks_requisition_bill`.`bill_prepared_by_resource`,`tasks_requisition_bill`.`bill_submitted_by_resource`,`tasks_requisition_bill`.`bill_edited_by_manager`,`tasks_requisition_bill`.`bill_approved_by_manager`,`tasks_requisition_bill`.`bill_edited_by_cfo`,`tasks_requisition_bill`.`bill_approved_by_cfo`,`tasks_requisition_bill`.`bill_edited_by_accountant`,`tasks_requisition_bill`.`bill_approved_by_accountant`) AS `all_requisition_datas` from `tasks_requisition_bill`;

DROP VIEW IF EXISTS `sites_datas`;
CREATE VIEW `sites_datas` AS select `sites`.`id` AS `id`,`sites`.`project_id` AS `project_id`,`sites`.`site_code` AS `site_code`,`sites`.`site_head` AS `site_head`,`sites`.`completion_status` AS `completion_status`,concat_ws(',',`sites`.`id`,`sites`.`project_id`,`sites`.`user_id`,`sites`.`location`,`sites`.`site_code`,`sites`.`material`,`sites`.`site_head`,`sites`.`budget`,`sites`.`completion_status`) AS `all_sites_datas` from `sites`;


DROP VIEW IF EXISTS `tasks_datas`;
CREATE VIEW `tasks_datas` AS select `tasks`.`id` AS `id`,`tasks`.`user_id` AS `user_id`,`tasks`.`task_name` AS `task_name`,`tasks`.`task_code` AS `task_code`,`tasks`.`task_type` AS `task_type`,`tasks`.`project_id` AS `project_id`,`tasks`.`site_head` AS `site_head`,`tasks`.`task_for` AS `task_for`,concat_ws(',',`tasks`.`id`,`tasks`.`user_id`,`tasks`.`task_name`,`tasks`.`task_code`,`tasks`.`task_type`,`tasks`.`project_id`,`tasks`.`site_head`,`tasks`.`task_details`,`tasks`.`anonymous_proof_details`,`tasks`.`task_assigned_to_head`,`tasks`.`task_for`,`tasks`.`manager_override_chunck`,`tasks`.`override_status`) AS `all_tasks_datas` from `tasks`;


DROP VIEW IF EXISTS `tasks_material_datas`;
CREATE VIEW `tasks_material_datas` AS select `materialsss`.`id` AS `id`,`materialsss`.`task_id` AS `task_id`,`materialsss`.`material_id` AS `material_id`,`materialsss`.`material_qty` AS `material_qty`,`materialsss`.`material_amount` AS `material_amount`,`materialsss`.`material_note` AS `material_note`,`materialsss`.`material_name` AS `material_name`,`materialsss`.`material_unit` AS `material_unit`,concat_ws(',',`materialsss`.`id`,`materialsss`.`task_id`,`materialsss`.`material_id`,`materialsss`.`material_qty`,`materialsss`.`material_amount`,`materialsss`.`material_note`,`materialsss`.`material_name`,`materialsss`.`material_unit`) AS `tasks_material_datas` from (select `tasks_material`.`id` AS `id`,`tasks_material`.`task_id` AS `task_id`,`tasks_material`.`material_id` AS `material_id`,`tasks_material`.`material_qty` AS `material_qty`,`tasks_material`.`material_amount` AS `material_amount`,`tasks_material`.`material_note` AS `material_note`,(select `materials`.`name` from `materials` where `materials`.`id` = `tasks_material`.`material_id` limit 0,1) AS `material_name`,(select `materials`.`unit` from `materials` where `materials`.`id` = `tasks_material`.`material_id` limit 0,1) AS `material_unit` from `tasks_material`) `materialsss`;

DROP VIEW IF EXISTS `tasks_site_datas`;
CREATE VIEW `tasks_site_datas` AS select `tasks_site`.`id` AS `id`,`tasks_site`.`task_id` AS `task_id`,`tasks_site`.`site_id` AS `site_id`,`tasks_site`.`resource_id` AS `resource_id`,concat_ws(',',`tasks_site`.`id`,`tasks_site`.`task_id`,`tasks_site`.`site_id`,`tasks_site`.`resource_id`) AS `all_tasks_sites_datas` from `tasks_site`;

DROP VIEW IF EXISTS `tasks_vehicle_datas`;
CREATE VIEW `tasks_vehicle_datas` AS select `ll`.`id` AS `id`,`ll`.`task_id` AS `task_id`,`ll`.`vehicle_id` AS `vehicle_id`,`ll`.`vehicle_rent` AS `vehicle_rent`,`ll`.`vehicle_note` AS `vehicle_note`,`ll`.`vehicle_name` AS `vehicle_name`,`ll`.`vehicle_size` AS `vehicle_size`,concat_ws(',',`ll`.`id`,`ll`.`task_id`,`ll`.`vehicle_id`,`ll`.`vehicle_rent`,`ll`.`vehicle_note`,`ll`.`vehicle_name`,`ll`.`vehicle_size`) AS `tasks_vehicle_datas` from (select `tasks_vehicle`.`id` AS `id`,`tasks_vehicle`.`task_id` AS `task_id`,`tasks_vehicle`.`vehicle_id` AS `vehicle_id`,`tasks_vehicle`.`vehicle_rent` AS `vehicle_rent`,`tasks_vehicle`.`vehicle_note` AS `vehicle_note`,(select `vehicles`.`name` from `vehicles` where `vehicles`.`id` = `tasks_vehicle`.`vehicle_id` limit 0,1) AS `vehicle_name`,(select `vehicles`.`size` from `vehicles` where `vehicles`.`id` = `tasks_vehicle`.`vehicle_id` limit 0,1) AS `vehicle_size` from `tasks_vehicle`) `ll`;

DROP VIEW IF EXISTS `ttrb`;
CREATE VIEW `ttrb` AS select `tasks`.`id` AS `id`,`tasks`.`user_id` AS `manager`,`tasks`.`task_name` AS `task_name`,`tasks`.`task_type` AS `task_type`,`tasks`.`project_id` AS `project_id`,`tasks`.`current_range_id` AS `current_range_id`,`tasks`.`site_head` AS `site_head`,`tasks`.`task_assigned_to_head` AS `task_assigned_to_head`,`tasks`.`task_for` AS `task_for`,`tasks`.`created_at` AS `task_created_at`,date_format(`tasks`.`created_at`,'%Y-%m-%d') AS `created_at_date`,`tasks_requisition_bill`.`id` AS `rid`,`tasks_requisition_bill`.`task_id` AS `task_id`,(select sum(`tasks_material_datas`.`material_amount`) AS `total_material_amount` from `tasks_material_datas` where `tasks_material_datas`.`task_id` = `tasks`.`id`) AS `total_material_amount`,(select sum(`tasks_vehicle_datas`.`vehicle_rent`) AS `total_vehicle_rent` from `tasks_vehicle_datas` where `tasks_vehicle_datas`.`task_id` = `tasks`.`id`) AS `total_vehicle_rent`,`tasks_requisition_bill`.`rpbm_amount` AS `rpbm_amount`,`tasks_requisition_bill`.`rebc_amount` AS `rebc_amount`,`tasks_requisition_bill`.`reba_amount` AS `reba_amount`,`tasks_requisition_bill`.`requisition_approved_by_accountant` AS `is_reba_approved`,`tasks_requisition_bill`.`bpbr_amount` AS `bpbr_amount`,`tasks_requisition_bill`.`bebm_amount` AS `bebm_amount`,`tasks_requisition_bill`.`bebc_amount` AS `bebc_amount`,`tasks_requisition_bill`.`beba_amount` AS `beba_amount`,`tasks_requisition_bill`.`created_at` AS `created_at` from (`tasks` left join `tasks_requisition_bill` on(`tasks`.`id` = `tasks_requisition_bill`.`task_id`));

DROP VIEW IF EXISTS `users_datas`;
CREATE VIEW `users_datas` AS select `users`.`id` AS `id`,`users`.`name` AS `name`,`users`.`email` AS `email`,`users`.`username` AS `username`,`users`.`phone` AS `phone`,`users`.`employee_no` AS `employee_no`,concat_ws(',',`users`.`id`,`users`.`name`,`users`.`email`,`users`.`employee_no`,`users`.`username`,`users`.`role`,`users`.`birthday`,`users`.`gender`,`users`.`marital_status`,`users`.`father`,`users`.`mother`,`users`.`address`,`users`.`district`,`users`.`postcode`,`users`.`phone`,`users`.`emergency_phone`,`users`.`company`,`users`.`designation`,`users`.`join_date`,`users`.`company_address`,`users`.`basic_salary`,`users`.`avatar`,`users`.`signature`,`users`.`bank_information`,`users`.`mbanking_information`,`users`.`alternative_email`,`users`.`employee_status`,`users`.`is_active`) AS `all_users_datas` from `users`;

